sudo: required
language: ruby
services:
  - docker
before_install:
  - git clone --depth 1 https://github.com/seiferma/Docker_BuildUtils.git /tmp/BuildUtils
  - . /tmp/BuildUtils/travisSetup.sh
script:
  - travisBuildDockerhub.sh
deploy:
  provider: script
  script: travisDeployDockerhub.sh
  on:
    branch: master
env:
  global: 
    - IMAGE_NAME=seiferma/alpine-glibc
    - secure: "UXfmKWBA3wqy2woRFKloWpVTtbZ8OiSaTBkazFNSlVO3Hz6eBh8p+zE+OaaRKgwzzyaoINxu4G7VcqZaUhvjWOVZw+duagOAmyRO80DzsJ6Wr+hk3yUGRrNLVcOofCv5fFLZRT4US80IAgDmzgnXI3ChimVa/P5oniFQQQefhuTCGaJ16lK9vqY/R4RFAeHdMWnjR0cEbNH3q5P5hu0UZGukO2NX72bww+a3y1Ch75JKRZnaHlvk9gyx54qpSFhkAivL9lEm25GyQiwkUxbomXiFkGxOEsjfcSKEGbhjhUXXZWRD5e9mTBpUxjtiG7FEAHUmmZdMQuEx2V8B4T8+IpR+sfghuueFKQD+8YMA2n78fgS3kTpNoAG44ZTFl/waLf2ttPQ0FQ0CHi/J/BCFfmqQKUL46r9JhkiL3iUYbMEig9xkmAn1WKebzkipdnYKLsCzxzLoAVnu4mxFi7S74PcEsSEOm2TuYkramEDuXOJefyv7g2PB4x0KY4gn1tmEMbVXbGvxbz4YbrJMSfh+VMXTqp90MasLYDs7Nw5DtDep1biSTCfgcHIUa2pIU1zzvXPTcMlcVtz7t2q/tPbG5nYRaGgbh1ie0TDDnXU71PPnP5MDDoFiGQ50bVkoM+OlwogmbeuXb4hOVUdnkL3qzjYmBTF1rGg9B4UNP7zBeSk="