sudo: required
language: ruby
services:
  - docker
before_install:
  - git clone --depth 1 https://github.com/seiferma/Docker_BuildUtils.git /tmp/BuildUtils
  - . /tmp/BuildUtils/travisSetup.sh
script:
  - travisBuildDockerhub.sh
deploy:
  provider: script
  script: travisDeployDockerhub.sh
  on:
    branch: master
env:
  global: 
    - IMAGE_NAME=seiferma/alpine-glibc
    - secure: "vqo03MthPka9FKHdYy82dTiaQ6m6NVGVf4W3hzQJO1+WnHwb1Tp4uOVd51zSegtzXMgt95R6nkzm86xPmMyKhFLmvgaeeWBDIHGx4OAbNDnksCWeiuQuGKP+A2AiQxV8AgGedMRN4atKzSTFYB9FFtPHBaNT0ZgKrgNo4Pi4KcMwqKz+/AmiAf9rhl1De/Uh0+qzY2VaTvakk7hA7S7NLmRDrcd52kIZxe3VtwxP0/eNg73QO6yJBuXpacFuoSbY4wTKIeBjZHOdYaqU2DT3NmjGtZScRI6woLwgcLTR3Z0kkcu7ImuVyGCZMcGTDxsjOfcta9m0ZFZk5gZJrqHngrtDbAQCd9cJGCHfVAPdyou/UJeeBskO/kKXLvT6hPYmROwhfGoYWrcGQ4g/H757Q809NXlrCV+L5yyFAIoCsN/R68GgTNQZ1ZMxvW8ZEzK4w/9v5/+iuIEeNDsLc7JYndWsNK/KOAiUqgH4Rsd9Y0NdyAsqvdz+mx0ATgwTVyVL1ayWWQX7JNIIhRRJnqET4cqFDdP32vH7u58aWoA6ps2ZV3Ep9P2sFNi16hA8VI+RKe66E7qXO31QE8aJvNqUsdx9+e8WZlLf98c2tRNuu7TdzSTRjP4/EMSWLI4MvddPXBqmWrT8tMUk3W6CEnSWTKQkVN6y5aXacpoL5G4QBv0="
